#!/bin/bash
# qjob_script (C) 2024 Ananya Adhikari 
# based on slurm_mpirun_script (C) 2013 Wolfgang Tichy
# needed for qjob

# Replace some parts of $MPIRUN and $MPIBOOT with the local env vars here:
##replace string $PBS_NODEFILE with content of env var $PBS_NODEFILE
#MPIBOOT=${MPIBOOT/\$PBS_NODEFILE/$PBS_NODEFILE}
#MPIRUN=${MPIRUN/\$PBS_NODEFILE/$PBS_NODEFILE}
#MPIHALT=${MPIHALT/\$PBS_NODEFILE/$PBS_NODEFILE}

# tell me what's happening:
echo "======================================================================"
echo $qjob
echo "----------------------------------------------------------------------"
echo "nodes = $nodes"
echo "ppn = $ppn"
echo "tpn = $tpn"
echo "procs = $procs"
echo "memory = $memory"
echo "walltime = $walltime"
echo "queue = $queue"
echo "constraint = $constraint"
echo "njobs = $njobs"
echo "account = $account"
echo "jobname = $jobname"
echo "command = $command"
echo "parfile = $parfile"
echo
echo "MPIBOOT = $MPIBOOT"
echo "MPIRUN = $MPIRUN"
echo "MPIHALT = $MPIHALT"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "Checking whether the following file exists:"
echo "$HOME/bin/qjob_exe_coms_start"
if [[ -f $HOME/bin/qjob_exe_coms_start ]]
then
  echo "Found file with potential list of commands to execute."
  echo "Starting to execute commands at $(date)."
  while IFS= read -r line; do
    echo "==================================="
    echo "Command:"
    echo "$line"
    echo "-----------"
    eval "$line"
  done < $HOME/bin/qjob_exe_coms_start
  echo "==================================="
  echo "Done executing commands at $(date)."
else
  echo "No commands to execute."
fi
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "Info about OpenMP and Slurm environment variable:"
echo
env | grep SLURM_
echo
env | grep OMP_
#echo "OMP_NUM_THREADS = $OMP_NUM_THREADS"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "sbatch command:"
echo "$QSUB"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "Package info:"
echo
if command -v module >/dev/null 2>&1; then
  echo "Modules loaded:"
  echo
  module list
fi
echo
if command -v spack >/dev/null 2>&1; then
  # Only print if *something* is actually loaded via Spack
  if spack find --loaded >/dev/null 2>&1 && [[ -n "$(spack find --loaded 2>/dev/null | sed -n 's/^[[:space:]]\+//p')" ]]; then
    echo "Spack loaded specs:"
    echo
    spack -vl find --loaded
  fi
fi
echo
echo "Important for Intel MPI:"
echo "MPIR_CVAR_CH4_OFI_TAG_BITS = $MPIR_CVAR_CH4_OFI_TAG_BITS"
echo "MPIR_CVAR_CH4_OFI_RANK_BITS = $MPIR_CVAR_CH4_OFI_RANK_BITS"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "The master node of this job is $(hostname)"
echo "The submission directory is $SLURM_SUBMIT_DIR"
# echo The master node of this job is `hostname`
# echo The submision directory is `echo $SLURM_SUBMIT_DIR`
echo The node list is $SLURM_NODELIST
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
# echo "Info of `hostname` from lscpu:"
echo "Info of $(hostname) from lscpu:"
echo
lscpu
echo
echo "free info:"
free -h
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
#echo This job runs on the following nodes:
#echo `cat $PBS_NODEFILE`
#echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

## make PBS go to current dir
#echo going to $PBS_O_WORKDIR
#cd $PBS_O_WORKDIR

echo
# echo "Job started on `hostname` at `date`"
echo "Job started on $(hostname) at $(date)"
echo "======================================================================"

if [ -n "${MPIBOOT}" ]
then
  $MPIBOOT
fi

time $MPIRUN

if [ -n "${MPIHALT}" ]
then
  $MPIHALT
fi

echo "======================================================================"
echo "Job ended at $(date)"
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "Checking whether the following file exists:"
echo "$HOME/bin/qjob_exe_coms_end"
if [[ -f $HOME/bin/qjob_exe_coms_end ]]
then
  echo "Found file with potential list of commands to execute."
  echo "Starting to execute commands at $(date)."
  while IFS= read -r line; do
    echo "==================================="
    echo "Command:"
    echo "$line"
    echo "-----------"
    eval "$line"
  done < $HOME/bin/qjob_exe_coms_end
  echo "==================================="
  echo "Done executing commands at $(date)."
else
  echo "No commands to execute."
fi
echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
# echo "Job Ended at `date`"
echo
